#
#    __                          __
#   / /____ ___ ____  ___  ___ _/ /       This file is provided to you by https://github.com/GITHUB_ORG/PROJECT_NAME
#  / __/ -_) _ `/ _ \/ _ \/ _ `/ /        Copyright YEAR ORG_NAME <ORG_EMAIL>
#  \__/\__/\_, /\___/_//_/\_,_/_/         It is licensed under Creative Commons Zero v1.0 Universal
#         /___/                           Please report bugs and contribute back your improvements
#
#                                         Version: v0.1.0-SNAPSHOT
###################################
name: Quality Assurance
on: [ push, pull_request ]

jobs:
  before_pr:
    name: before-pr.sh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install shellcheck
        run: ./lib/tegonal-scripts/src/ci/install-shellcheck.sh
      - name: before-pr.sh
        run: ./scripts/before-pr.sh

  todo_checker:
    name: check for TODOs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check for TODOs
        uses: tegonal/workflow-helper@v0.3.0
        with:
          commands: todo-checker
